version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "{{ cookiecutter.project_name }}"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-6hprfrwt4obw"
s3_prefix = "{{ cookiecutter.project_name }}"
region = "{{ cookiecutter.region }}"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
